# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end
events = [
  {
    id: '97d64e90-2c53-41cf-a6a5-af399f75ecc5',
    name: 'Connect.Tech 2023',
    description:
      'The largest multi-framework front-end conference in the USA. A three day event diving deep with experts from across the tech ecosystem.',
    timezone: 'America/New_York',
    start_at: DateTime.parse('October 24, 2023 08:00:00'),
    end_at: DateTime.parse('October 26, 2023 05:00:00'),
    venue_type: 'IN_PERSON',
    venue_name: 'Georgia World Congress Center',
    address: '285 Andrew Young International Blvd NW',
    country: 'USA',
    city: 'Atlanta',
    state_or_province: 'GA',
    postal_code: '30313',
    registration_start_at: DateTime.parse('May 1, 2023 08:00:00'),
    registration_end_at: DateTime.parse('September 15, 2023 23:59:59'),
    currency: 'USD',
    capacity: nil,
  },
  {
    id: '97d64e90-2c53-41cf-a6a5-af399f75ecc6',
    name: 'Connect.Tech 2024',
    description:
      'The largest multi-framework front-end conference in the USA. A three day event diving deep with experts from across the tech ecosystem.',
    timezone: 'America/New_York',
    start_at: DateTime.parse('October 24, 2024 08:00:00'),
    end_at: DateTime.parse('October 26, 2024 05:00:00'),
    venue_type: 'IN_PERSON',
    venue_name: 'Georgia World Congress Center',
    address: '285 Andrew Young International Blvd NW',
    country: 'USA',
    city: 'Atlanta',
    state_or_province: 'GA',
    postal_code: '30313',
    registration_start_at: DateTime.parse('May 1, 2024 08:00:00'),
    registration_end_at: DateTime.parse('September 15, 2024 23:59:59'),
    currency: 'USD',
    capacity: nil,
  },
  {
    id: '97d64e90-2c53-41cf-a6a5-af399f75ecc7',
    name: 'Connect.Tech 2025',
    description:
      'The largest multi-framework front-end conference in the USA. A three day event diving deep with experts from across the tech ecosystem.',
    timezone: 'America/New_York',
    start_at: DateTime.parse('October 24, 2025 08:00:00'),
    end_at: DateTime.parse('October 26, 2025 05:00:00'),
    venue_type: 'IN_PERSON',
    venue_name: 'Georgia World Congress Center',
    address: '285 Andrew Young International Blvd NW',
    country: 'USA',
    city: 'Atlanta',
    state_or_province: 'GA',
    postal_code: '30313',
    registration_start_at: DateTime.parse('May 1, 2025 08:00:00'),
    registration_end_at: DateTime.parse('September 15, 2025 23:59:59'),
    currency: 'USD',
    capacity: nil,
  },
  {
    id: '97d64e90-2c53-41cf-a6a5-af399f75ecc8',
    name: 'Connect.Tech 2026',
    description:
      'The largest multi-framework front-end conference in the USA. A three day event diving deep with experts from across the tech ecosystem.',
    timezone: 'America/New_York',
    start_at: DateTime.parse('October 24, 2026 08:00:00'),
    end_at: DateTime.parse('October 26, 2026 05:00:00'),
    venue_type: 'IN_PERSON',
    venue_name: 'Georgia World Congress Center',
    address: '285 Andrew Young International Blvd NW',
    country: 'USA',
    city: 'Atlanta',
    state_or_province: 'GA',
    postal_code: '30313',
    registration_start_at: DateTime.parse('May 1, 2026 08:00:00'),
    registration_end_at: DateTime.parse('September 15, 2026 23:59:59'),
    currency: 'USD',
    capacity: nil,
  },
  {
    id: '97d64e90-2c53-41cf-a6a5-af399f75ecc9',
    name: 'Connect.Tech 2027',
    description:
      'The largest multi-framework front-end conference in the USA. A three day event diving deep with experts from across the tech ecosystem.',
    timezone: 'America/New_York',
    start_at: DateTime.parse('October 24, 2027 08:00:00'),
    end_at: DateTime.parse('October 26, 2027 05:00:00'),
    venue_type: 'IN_PERSON',
    venue_name: 'Georgia World Congress Center',
    address: '285 Andrew Young International Blvd NW',
    country: 'USA',
    city: 'Atlanta',
    state_or_province: 'GA',
    postal_code: '30313',
    registration_start_at: DateTime.parse('May 1, 2027 08:00:00'),
    registration_end_at: DateTime.parse('September 15, 2027 23:59:59'),
    currency: 'USD',
    capacity: nil,
  },
  {
    id: '97d64e90-2c53-41cf-a6a5-af399f75ecc1',
    name: 'Connect.Tech 2028',
    description:
      'The largest multi-framework front-end conference in the USA. A three day event diving deep with experts from across the tech ecosystem.',
    timezone: 'America/New_York',
    start_at: DateTime.parse('October 24, 2028 08:00:00'),
    end_at: DateTime.parse('October 26, 2028 05:00:00'),
    venue_type: 'IN_PERSON',
    venue_name: 'Georgia World Congress Center',
    address: '285 Andrew Young International Blvd NW',
    country: 'USA',
    city: 'Atlanta',
    state_or_province: 'GA',
    postal_code: '30313',
    registration_start_at: DateTime.parse('May 1, 2028 08:00:00'),
    registration_end_at: DateTime.parse('September 15, 2028 23:59:59'),
    currency: 'USD',
    capacity: nil,
  },
  {
    id: '97d64e90-2c53-41cf-a6a5-af399f75ecc2',
    name: 'Connect.Tech 2029',
    description:
      'The largest multi-framework front-end conference in the USA. A three day event diving deep with experts from across the tech ecosystem.',
    timezone: 'America/New_York',
    start_at: DateTime.parse('October 24, 2029 08:00:00'),
    end_at: DateTime.parse('October 26, 2029 05:00:00'),
    venue_type: 'IN_PERSON',
    venue_name: 'Georgia World Congress Center',
    address: '285 Andrew Young International Blvd NW',
    country: 'USA',
    city: 'Atlanta',
    state_or_province: 'GA',
    postal_code: '30313',
    registration_start_at: DateTime.parse('May 1, 2029 08:00:00'),
    registration_end_at: DateTime.parse('September 15, 2029 23:59:59'),
    currency: 'USD',
    capacity: nil,
  }
]
events.each do |event|
  Event.find_or_create_by!(event)
end
